[package]
name = "kcm"
description = "Application to conviniently switch between kubectl contexts"
version = "0.1.0"
edition = "2021"
authors = ["Juan Lavorano"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.7.5"

